title: Machine Learning
remote_theme: pmarsceill/just-the-docs
description:  Machine learning study notes
color_scheme: nil
search_enabled: true
search_tokenizer_separator: /[\s/]+/

footer_content: "Copyright &copy; 2020 Akash Panchal. Distributed by an <a href=\"https://github.com/akashp1712/ml-akash/tree/master/LICENSE.txt\">MIT license.</a>"
