title: Machine Learning
remote_theme: pmarsceill/just-the-docs
description:  Machine learning study notes
baseurl: "/ml-akash"
url: "https://akashp1712.github.io"
permalink: pretty
color_scheme: nil
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "ML-Akash on GitHub":
    - "//github.com/akashp1712/ml-akash"
footer_content: "Copyright &copy; 2020 Akash Panchal. Distributed by an <a href=\"https://github.com/akashp1712/ml-akash/tree/master/LICENSE.txt\">MIT license.</a>"
